:zap: determine colorization automatically
nonebot/nonebot2 pull request #1034
Opened 2022-06-03 10:35 UTC by BlueGlassBlock

Decoding error may be raised when escape sequences couldn't be handled correctly.

2022-06-03 10:59 UTC, synodriver commented
这个logger改了可能影响有点大……

2022-06-03 11:28 UTC, yanyongyu requested changes
直接删了就行

2022-06-03 11:28 UTC, yanyongyu commented on nonebot/log.py
> +    colorize=None,  # determine colorization automatically
```suggestion
```

2022-06-03 11:32 UTC, yanyongyu commented
> 这个logger改了可能影响有点大……

并不影响logger的行为，只要terminal支持颜色默认还是彩色的

2022-06-03 12:04 UTC, BlueGlassBlock commented
done. squash就好

2022-06-03 12:59 UTC, merged

2022-06-27 13:53 UTC, NekoAria commented
但是这样一来，用 `pm2` 托管的话，日志也没有彩色了。
其他守护进程程序我没试过，不清楚是否也会受此影响。

2022-06-27 13:56 UTC, NekoAria commented
能否加个配置项让用户自己设置呢？
比如：
```python
log_colorize = False  # 默认
```