Feature: on_函数族支持 expire_time 参数
nonebot/nonebot2 pull request #1106
Opened 2022-07-19 08:15 UTC by Dobiichi-Origami

2022-07-19 08:28 UTC, Well2333 submitted a review, later dismissed

2022-07-19 08:37 UTC, MingxuanGame approved these changes

2022-07-19 08:51 UTC, yanyongyu requested changes
把CommandGroup的docstring也改一下吧，kwargs现在应该改成具体的参数了

2022-07-20 01:45 UTC, yanyongyu submitted a review, later dismissed

2022-07-20 02:20 UTC, yanyongyu approved these changes

2022-07-20 02:21 UTC, merged