Feature: 添加 State 响应器触发消息
nonebot/nonebot2 pull request #1315
Opened 2022-10-10 14:08 UTC by A-kirami

2022-10-10 14:57 UTC, yanyongyu reviewed
在state里不能用一个key，会出现覆盖的情况，比如rule为`startswith("xxx") & endswith("xxx")`

2022-10-10 15:06 UTC, A-kirami commented
> 在state里不能用一个key，会出现覆盖的情况，比如rule为`startswith("xxx") & endswith("xxx")`

忘了这种情况，那还是分别设置key比较好

2022-10-11 11:36 UTC, yanyongyu requested changes

2022-10-11 11:36 UTC, yanyongyu commented on nonebot/rule.py
> +        if match:
match都改成海象表达式吧

2022-10-11 11:36 UTC, yanyongyu commented on nonebot/rule.py
> +        if match:
这里也是

2022-10-11 11:36 UTC, yanyongyu commented on nonebot/rule.py
> +        return False
```suggestion
        if key := next((k for k in self.keywords if k in text), None):
            state[KEYWORD_KEY] = key
            return True
        return False
```

2022-10-11 11:36 UTC, yanyongyu commented on nonebot/rule.py
> +        return False
```suggestion
        if text in self.msg:
            state[FULLMATCH_KEY] = text
            return True
        return False
```

2022-10-11 11:36 UTC, yanyongyu commented on tests/test_rule.py
> +        msg = (msg,)
这里不如把第76行的assert一起改了，复用变量

2022-10-11 11:36 UTC, yanyongyu commented on tests/test_rule.py
> +        msg = (msg,)
这里也是

2022-10-11 11:36 UTC, yanyongyu commented on tests/test_rule.py
> +        msg = (msg,)
这里也是

2022-10-11 16:44 UTC, yanyongyu approved these changes

2022-10-12 05:41 UTC, merged