__getattr__ should not response to special methods
nonebot/nonebot2 pull request #1398
Opened 2022-11-16 08:17 UTC by synodriver

不要截胡魔术方法，不然可能发生坏事

2022-11-18 04:04 UTC, yanyongyu requested changes

2022-11-18 04:04 UTC, yanyongyu commented on nonebot/internal/adapter/bot.py
> +            raise AttributeError
加上错误信息

2022-11-18 05:13 UTC, synodriver commented on nonebot/internal/adapter/bot.py
> +            raise AttributeError
加什么比较好呢

2022-11-18 05:52 UTC, yanyongyu commented on nonebot/internal/adapter/bot.py
> +            raise AttributeError
就照着python原本那样写吧

2022-11-19 07:20 UTC, synodriver commented
改好了

2022-11-19 08:11 UTC, yanyongyu approved these changes

2022-11-19 08:14 UTC, merged