Feature: 商店支持模糊搜索
nonebot/nonebot2 pull request #1547
Opened 2023-01-04 11:05 UTC by A-kirami

resolve #1527

2023-01-04 11:28 UTC, yanyongyu commented
你这样写真的不会报错吗，不要用正则过滤，模糊匹配不是正则啊喂

2023-01-04 11:30 UTC, A-kirami commented
> 你这样写真的不会报错吗，不要用正则过滤，模糊匹配不是正则啊喂

测试过了，不会报错啊

2023-01-04 15:38 UTC, yanyongyu commented
你输入一个非正则语法的东西

2023-01-04 15:41 UTC, closed without merging

2023-01-04 15:41 UTC, yanyongyu requested changes
换种模糊搜索算法吧

2023-01-05 05:38 UTC, mnixry commented
可以试试计算Levenshtein距离然后排序？