Docs: 重写教程与进阶指南
nonebot/nonebot2 pull request #1604
Opened 2023-01-19 11:23 UTC by yanyongyu

2023-01-19 12:58 UTC, mnixry commented on website/docs/editor-support.md
> +框架基于 [PEP484](https://www.python.org/dev/peps/pep-0484/)、[PEP 561](https://www.python.org/dev/peps/pep-0561/)、[PEP8](https://www.python.org/dev/peps/pep-0008/) 等规范进行开发并且是 **Fully Typed**。框架使用 `pyrigh
```suggestion
框架基于 [PEP484](https://www.python.org/dev/peps/pep-0484/)、[PEP 561](https://www.python.org/dev/peps/pep-0561/)、[PEP8](https://www.python.org/dev/peps/pep-0008/) 等规范进行开发并且是 **拥有完整类型支持 (aka Fully Typed)**。框架使用 `pyright`（`Pylance`）工具进行类型检查，确保代码可以被编辑器正确解析。
```

2023-01-19 12:58 UTC, mnixry commented on website/docs/question.md
> +   NoneBot：[![NoneBot2](https://img.shields.io/github/stars/nonebot/nonebot2?style=social)](https://github.com/nonebot/nonebot2)
```suggestion
   NoneBot：[![NoneBot project link](https://img.shields.io/github/stars/nonebot/nonebot2?style=social)](https://github.com/nonebot/nonebot2)
```

2023-01-19 12:58 UTC, mnixry commented on website/docs/tutorial/quick-start.mdx
> +- 如果没有使用虚拟环境，请卸载已安装的 NoneBot v1！！！
```suggestion
- **我们强烈建议您使用虚拟环境进行开发**，如果没有使用虚拟环境，请确保已经卸载可能存在的 NoneBot v1！！！
```

2023-03-19 10:36 UTC, Well2333 requested changes

2023-03-19 10:36 UTC, Well2333 commented on website/docs/tutorial/application.md
**创建一个 NoneBot 项目** 应更名为 **手动创建一个 NoneBot 项目** 或类似的名字，避免与nb-cli创建项目混淆

2023-03-19 10:40 UTC, StarHeartHunt requested changes

2023-03-19 10:40 UTC, StarHeartHunt commented on website/docs/tutorial/application.md
> +# 创建一个项目
```suggestion
# 手动创建项目
```

2023-03-19 10:40 UTC, StarHeartHunt commented on website/docs/README.md
> +NoneBot2 是一个现代、跨平台、可扩展的 Python 聊天机器人框架（下称 NoneBot），它基于 Python 的类型注解和异步优先特性（兼容同步），能够为你的需求实现提供便捷灵活的支持。同时，拥有大量的开发者为其开发插件，可以不进行任何代码编写，仅需要完成环境配置及插件安装后便可正常使用。
```suggestion
NoneBot2 是一个现代、跨平台、可扩展的 Python 聊天机器人框架（下称 NoneBot），它基于 Python 的类型注解和异步优先特性（兼容同步），能够为你的需求实现提供便捷灵活的支持。同时，NoneBot 拥有大量的开发者为其开发插件，可以不进行任何代码编写，仅需要完成环境配置及插件安装后便可正常使用。
```

2023-03-19 10:40 UTC, StarHeartHunt commented on website/docs/tutorial/create-plugin.md
> +如果你使用的 `nb-cli` 进行的插件管理，那么你可以跳过这一节，`nb-cli` 将会自动处理加载。
```suggestion
如果你使用 `nb-cli` 进行插件管理，那么你可以跳过这一节，`nb-cli` 将会自动处理加载。
```

2023-03-19 11:08 UTC, j1g5awi commented on website/docs/tutorial/create-plugin.md
> +如果你使用的 `nb-cli` 进行的插件管理，那么你可以跳过这一节，`nb-cli` 将会自动处理加载。
「进行插件管理」->「管理插件」

2023-03-19 11:21 UTC, lgc2333 commented on website/docs/appendices/config.mdx
> +DICT__K3=v2
```suggestion
DICT__K3=v3
```
emm

2023-03-19 13:02 UTC, j1g5awi requested changes

2023-03-19 13:02 UTC, j1g5awi commented on website/docs/tutorial/matcher.md
> +这样，我们就获得一个名为 `weather` 的事件响应器了，这个事件响应器会对 `[命令头]天气` 开头的命令进行响应。
命令头...

2023-03-20 02:09 UTC, StarHeartHunt commented
nb-cli 或许可以在称呼时换成 NoneBot CLI，仅在必须使用包名称呼时使用 `nb-cli`

2023-03-20 15:50 UTC, yanyongyu commented on website/docs/advanced/adapter.md
> +- **消息序列**：负责正确序列化消息，以便机器人插件处理。
这个Bot不知道怎么翻译啊

2023-03-24 07:02 UTC, StarHeartHunt approved these changes

2023-03-24 07:42 UTC, StarHeartHunt submitted a review, later dismissed

2023-03-24 08:16 UTC, StarHeartHunt approved these changes

2023-03-24 08:32 UTC, j1g5awi approved these changes

2023-03-24 08:34 UTC, merged