Docs: 使用 issue 表单替换 issue 模板
nonebot/nonebot2 pull request #1928
Opened 2023-04-16 07:35 UTC by A-kirami

2023-04-20 02:20 UTC, yanyongyu requested changes
槽点有点多，有空再改

2023-04-20 02:20 UTC, yanyongyu commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +        - Other
```suggestion
      description: 选择运行 NoneBot 的系统
      options:
        - Windows
        - MacOS
        - Linux
        - Other
```

2023-04-20 02:20 UTC, yanyongyu commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      required: true
这里不要用dropdown

2023-04-20 02:20 UTC, yanyongyu commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      placeholder: 2.0.0
```suggestion
      label: NoneBot 版本
      description: 运行的 NoneBot 版本
      placeholder: e.g. 2.0.0
```

2023-04-20 06:57 UTC, StarHeartHunt requested changes
既然内容都换中文了那都换了吧要不（

2023-04-20 06:57 UTC, StarHeartHunt commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +description: Create a bug report to help us improve
```suggestion
description: 提交 Bug 反馈以帮助我们改进代码
```

2023-04-20 06:57 UTC, StarHeartHunt commented on .github/ISSUE_TEMPLATE/feature_request.yml
> +description: Suggest an idea for this project
```suggestion
name: 特性建议
title: "Feature: 特性描述"
description: 提出关于项目新特性的想法
```

2023-04-23 03:48 UTC, yanyongyu commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      placeholder: e.g. 2.0.0
```suggestion
      description: 填写运行 NoneBot 的 Python 版本
      placeholder: e.g. 2.0.0
```

2023-04-23 03:48 UTC, yanyongyu commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      description: 运行的 NoneBot 版本
```suggestion
      label: NoneBot 版本
      description: 填写 NoneBot 版本
```

2023-04-23 03:48 UTC, yanyongyu commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      required: true
```suggestion
  - type: input
    id: env-adapter
    attributes:
      label: 适配器
      description: 填写使用的适配器以及版本
      placeholder: e.g. OneBot v11 2.2.2
    validations:
      required: true
```

2023-04-23 03:48 UTC, yanyongyu commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      required: true
```suggestion
  - type: input
    id: env-protocol
    attributes:
      label: 协议端
      description: 填写连接 NoneBot 的协议端及版本
      placeholder: e.g. go-cqhttp 1.0.0
    validations:
      required: true
```

2023-04-23 03:48 UTC, yanyongyu commented on .github/ISSUE_TEMPLATE/feature_request.yml
> +      required: true
```suggestion
  - type: textarea
    id: problem
    attributes:
      label: 希望能解决的问题
      description: 在使用中遇到什么问题而需要新的功能？
    validations:
      required: true
```

2023-04-23 03:48 UTC, yanyongyu commented on .github/ISSUE_TEMPLATE/feature_request.yml
> +      required: true
```suggestion
  - type: textarea
    id: feature
    attributes:
      label: 描述所需要的功能
      description: 请说明需要的功能或解决方法
    validations:
      required: true
```

2023-04-23 03:57 UTC, yanyongyu approved these changes

2023-04-23 03:58 UTC, merged