:memo: update export-and-require doc
nonebot/nonebot2 pull request #197
Opened 2021-02-06 09:35 UTC by AkiraXie

2021-02-06 10:22 UTC, mnixry requested changes
有几个小细节需要注意一下

另外, 可以[点击这里](https://deploy-preview-197--nb2-dev.netlify.app/next/advanced/export-and-require.html)或者在下方checks中的`netlify/nb2-dev/deploy-preview`查看修改后的文档预览

2021-02-06 10:22 UTC, mnixry commented on docs/advanced/export-and-require.md
> +:::warning  提示  使用这个方法进行跨插件访问时，**需要先加载`导出对象`的插件，再加载`导入对象`的插件。**
这个地方的格式有点问题
```suggestion
:::warning  提示  
使用这个方法进行跨插件访问时， **需要先加载`导出对象`的插件，再加载`导入对象`的插件。**
:::
```

2021-02-06 10:22 UTC, mnixry commented on docs/advanced/export-and-require.md
> +除了使用`export[key]=value`方法导出对象外，还支持`export.key=value`导出对象：
```suggestion
除了使用`export[key]=value`方法导出对象外，还支持通过设置属性`export.key=value`导出对象：
```

2021-02-06 10:22 UTC, mnixry commented on docs/advanced/export-and-require.md
> +对于`python 3.9`以上版本，还可以这样：
https://github.com/nonebot/nonebot2/blob/050137fb3f40d60faf910fe9b755d679f283fa4f/nonebot/plugin.py#L63-L66
感觉好像没有什么依赖`python 3.9`特性的地方?

2021-02-06 10:22 UTC, mnixry commented on docs/advanced/export-and-require.md
> +在`pluginB`中，我们调用`require`机制`导入对象`。
这个地方似乎需要加一句说明
```suggestion
在`pluginB`中，我们调用`require`机制`导入对象`。

::: warning 警告
在导入来自其他插件的对象时, 请确保导出该对象的插件在引用该对象的插件之前加载
:::
```

2021-02-06 10:47 UTC, AkiraXie commented on docs/advanced/export-and-require.md
> +对于`python 3.9`以上版本，还可以这样：
可以看一下 class export 的注释

2021-02-06 10:48 UTC, AkiraXie commented on docs/advanced/export-and-require.md
> +在`pluginB`中，我们调用`require`机制`导入对象`。
虽然在前面已经警告过了...不过确实还是再警告一下比较好

2021-02-06 10:51 UTC, mnixry commented on docs/advanced/export-and-require.md
> +对于`python 3.9`以上版本，还可以这样：
https://github.com/nonebot/nonebot2/blob/050137fb3f40d60faf910fe9b755d679f283fa4f/nonebot/plugin.py#L38-L61
貌似说的是
```python
@nonebot.export().sub
def foo():
    pass
```
这种语法在3.9以下不能工作, 你这里少写了几个字(

2021-02-06 11:02 UTC, AkiraXie commented on docs/advanced/export-and-require.md
> +对于`python 3.9`以上版本，还可以这样：
你理解反了应该... .sub可以工作直接export（）不可以工作。不过我理解的也有问题，等会儿都改下

2021-02-07 02:57 UTC, yanyongyu requested changes

2021-02-07 02:57 UTC, yanyongyu commented on docs/advanced/export-and-require.md
> +export["funcA"] = funcA
```suggestion
export.sub.funcA = funcA

export.funcA = funcA
```

2021-02-07 02:57 UTC, yanyongyu commented on docs/advanced/export-and-require.md
> +```
```suggestion
```python
export.vA = varA
export.fA = funcA
```
```

2021-02-07 02:57 UTC, yanyongyu commented on docs/advanced/export-and-require.md
> +```
```suggestion
除此之外，也支持 `嵌套` 导出对象：

```python
export.sub.vA = varA
export.sub.fA = funcA
```

```

2021-02-07 02:57 UTC, yanyongyu commented on docs/advanced/export-and-require.md
> + 在导入来自其他插件的对象时, 请确保导出该对象的插件在引用该对象的插件之前加载。
```suggestion
 在导入来自其他插件的对象时, 请确保导出该对象的插件在引用该对象的插件之前加载。如果该插件并未被加载，则会尝试加载。
```

2021-02-07 02:57 UTC, yanyongyu commented on docs/advanced/export-and-require.md
> +```
```suggestion
在之前，这个字典已经存入了`'vA'`-`varA`, `'fA'`-`funcA`或`'funcA'`-`funcA`这样的`key`-`value`对。因此在这里我们直接用`属性`的方法来获取导入对象: 

```python
varA = require_A.vA
funcA = require_A.fA or require_A.funcA
```
```

2021-02-07 03:00 UTC, yanyongyu approved these changes

2021-02-07 03:01 UTC, merged