Docs: 完成发布插件教程
nonebot/nonebot2 pull request #2078
Opened 2023-06-02 16:50 UTC by NCBM

完成发布插件教程

2023-06-03 09:01 UTC, Well2333 requested changes

2023-06-03 09:01 UTC, Well2333 commented on website/docs/developer/plugin-publishing.md
存在以下几点问题

1. 不应使用 setuptools 作为主要示范，对于绝大部分插件来说 poetry 及 pdm 相对会更简单且低错误
2. 教程前后关于发布pypi的部分过于割裂，没有前后文的必然性
3. 继第二点，此教程本身就不应该包含发布至pypi的内容，如果连发pypi都需要这篇文档单独教的话还是别发了比较好

2023-06-03 09:05 UTC, yanyongyu commented on website/docs/developer/plugin-publishing.md
这边建议用tab组件展示多种工具配置和使用方式

2023-06-03 09:16 UTC, Well2333 commented on website/docs/developer/plugin-publishing.md
以下是我个人的一点想法，列了个大纲，可以参考一下

# 发布插件

## 发布插件需要什么

1. 项目主页
2. 发布至 pypi
3. 包含 pluginmetadata

## 建议的项目结构

列出**推荐的项目结构**，但注明这**不是强制的**，实际上只要能跑就行

可以注明一下插件名的命名规范

### 使用第三方项目模板

可以推荐一波明见佬的项目模板

## pluginmetadata

注明其位置，还有2.0.0的兼容性

## 商店审核

注明需要完成以上全部任务后再发布商店

注明审核失败不要重开新的issue

2023-06-03 14:48 UTC, NCBM commented on website/docs/developer/plugin-publishing.md
文档已更改

2023-06-03 15:06 UTC, NCBM commented
是否需要在当前 PR 中更新“插件信息”章节？

2023-06-03 16:47 UTC, Well2333 submitted a review, later dismissed

2023-06-03 16:48 UTC, Well2333 commented
> 是否需要在当前 PR 中更新“插件信息”章节？

我觉得可以单开个PR

2023-06-03 16:51 UTC, Well2333 commented on website/docs/developer/plugin-publishing.mdx
> +1. 插件必须填写 `nonebot2` 依赖，如果只打算支持正式版请锁定到 `>=2.0.0`，否则应使用预览版本号进行锁定；
这里其实不是必须填写 nonebot2 作为依赖，因为适配器也会依赖 nonebot2 ，如果插件对 nonebot2 版本没有特殊要求（例如仅支持 2.0.0）的情况下是不必额外声明 nonebot2 的

不过这里是否需要保留我持中立态度，写不写均可

2023-06-03 16:55 UTC, Well2333 commented on website/docs/developer/plugin-publishing.mdx
> +3. `nonebot` 是 NoneBot1 的包，注意与 `nonebot2` 区分，**不要**写入插件的依赖列表；
这里的表述可以改成

由于 `nonebot` 是指 nonebot1 而不是 nonebot2，请注意添加依赖时**不要**将 `nonebot` 添加为依赖，以免造成冲突

2023-06-03 17:36 UTC, Well2333 commented on website/docs/developer/plugin-publishing.mdx
> +3. 由于 `nonebot` 是指 `nonebot1` **而非** `nonebot2`，因此要注意**不要**将 `nonebot1` 添加为插件的依赖，以免造成冲突；
> 因此要注意**不要**将 `nonebot1` 添加为插件的依赖

此处应该是 `nonebot`

2023-06-03 17:45 UTC, NCBM commented on website/docs/developer/plugin-publishing.mdx
> +3. 由于 `nonebot` 是指 `nonebot1` **而非** `nonebot2`，因此要注意**不要**将 `nonebot1` 添加为插件的依赖，以免造成冲突；
已修正

2023-06-05 03:01 UTC, yanyongyu reviewed
大概看了下主要几个问题：
1. 应该以开发者第一人称描述文档，如使用“我们”
2. 全部以 NoneBot 指代 NoneBot2
3. 文档描述的语句读上去还是有点别扭或者有点单调，不够丰富（

2023-06-05 04:12 UTC, NCBM commented on website/docs/developer/plugin-publishing.mdx
> +```
已修改

2023-06-11 13:04 UTC, he0119 requested changes

2023-06-11 13:04 UTC, he0119 commented on website/docs/developer/plugin-publishing.mdx
> +插件发布 Issue 创建后，将会经过 **Noneflow Bot** 的自动前置检查，以确保插件信息正确无误、插件能被正确加载。
```suggestion
插件发布 Issue 创建后，将会经过 **NoneFlow Bot** 的自动前置检查，以确保插件信息正确无误、插件能被正确加载。
```

2023-06-11 13:55 UTC, he0119 approved these changes

2023-06-11 15:32 UTC, yanyongyu commented on website/docs/developer/plugin-publishing.mdx
> +完成这些步骤后，您的插件将会被自动合并到[商店](/store)，而您也将成为 **[NoneBot 贡献者](https://github.com/nonebot/nonebot2/graphs/contributors)** 的一员。
```suggestion
完成这些步骤后，您的插件将会被自动合并到[商店](/store)，而您也将成为 [**NoneBot 贡献者**](https://github.com/nonebot/nonebot2/graphs/contributors)的一员。
```

2023-06-11 15:32 UTC, yanyongyu commented on website/docs/developer/plugin-publishing.mdx
> +在弹出的插件信息提交表单内，填入您所要发布的相应插件信息。
```suggestion
在弹出的插件信息提交表单内，填入您所要发布的相应插件信息。请注意，如果插件需要必要配置项才能正常导入，请在“插件配置项”中填写必要的内容（请勿填写密钥等敏感信息）。
```

2023-06-11 15:36 UTC, yanyongyu approved these changes

2023-06-11 15:41 UTC, merged