Docs: 适配器编写教程
nonebot/nonebot2 pull request #2079
Opened 2023-06-03 09:05 UTC by CMHopeSunshine

写不动了)

2023-06-03 17:10 UTC, synodriver commented on website/docs/developer/adapter-writing.md
> +	async def _forward_ws(self, bot: Bot):
这行怎么回事

2023-06-03 17:10 UTC, synodriver commented on website/docs/developer/adapter-writing.md
> +	async def _forward_ws(self, bot: Bot):
错误的缩进

2023-06-04 10:12 UTC, yanyongyu reviewed
文档应该以开发者第一人称编写，如：我们

2023-06-05 09:30 UTC, A-kirami requested changes

2023-06-05 09:30 UTC, A-kirami commented on website/docs/developer/adapter-writing.md
> +- [OneBot](https://github.com/nonebot/adapter-onebot/blob/master/nonebot/adapters/onebot/v11/message.py#LL76-L254)
```suggestion
- [OneBot](https://github.com/nonebot/adapter-onebot/blob/master/nonebot/adapters/onebot/v11/message.py#L77-L261)
```

更新一下行数

2023-06-06 09:41 UTC, MingxuanGame commented on website/docs/developer/adapter-writing.md
> +`Websocket 客户端`需要一个`ForwardDriver`类型的驱动器，例如`httpx`和`websockets`
```suggestion
`Websocket 客户端`需要一个支持WebSocket 的 `ForwardDriver`类型的驱动器，例如`aiohttp`和`websockets`
```

2023-06-07 06:53 UTC, MingxuanGame commented
怎么把readme写到这里了

2023-06-07 06:54 UTC, CMHopeSunshine commented
> 怎么把readme写到这里了

提交错分支了）

2023-07-13 03:52 UTC, 17TheWord commented
没有对齐 https://github.com/CMHopeSunshine/nonebot2/blob/be835dd2c4d73083f953d60baf7bd78e2a571596/website/docs/developer/adapter-writing.md?plain=1#L205

2023-07-13 03:54 UTC, mute23-code commented on website/docs/developer/adapter-writing.md
> +           return event_class.parse_obj(payload)
这里的换行好像有问题（
```suggestion
            return event_class.parse_obj(payload)
```

2023-07-18 03:42 UTC, yanyongyu requested changes

2023-07-18 03:42 UTC, yanyongyu commented on website/docs/developer/adapter-writing.md
> +具体为将请求构造为 NoneBot 提供的`Request`对象，调用`adapter`的`request`方法来发送请求。
这里应该区分两种连接情况来说明。下面示例也是。

```suggestion
我们需要实现 `Adapter` 的 `_call_api` 方法，使开发者能够调用平台提供的 API。如果通过 WebSocket 通信可以通过 `send` 方法来发送数据，如果采用 HTTP 请求，则需要通过 NoneBot 提供的 `Request` 对象，调用 `driver` 的 `request` 方法来发送请求。
```

2023-07-18 03:42 UTC, yanyongyu commented on website/docs/developer/adapter-writing.md
> +        return await self.adapter.request(request)
```suggestion
        return await self.driver.request(request)
```

2023-07-18 03:42 UTC, yanyongyu commented on website/docs/developer/adapter-writing.md
> +- [QQGuild](https://github.com/nonebot/adapter-qqguild/blob/master/nonebot/adapters/qqguild/adapter.py#L353-L359)
这里的示例都放进来，分WS和HTTP。

2023-07-18 03:42 UTC, yanyongyu commented on website/docs/developer/adapter-writing.md
> +#### 示例参考
这块和上面合并，不用这么详细

2023-07-18 03:42 UTC, yanyongyu commented on website/docs/developer/adapter-writing.md
> +我们需要继承基类`Bot`，并实现相关方法：
```suggestion
Bot 是机器人开发者能够直接获取并使用的核心对象，负责存储平台机器人相关信息，并提供回复事件、调用 API 的上层方法。我们需要继承基类 `Bot`，并实现相关方法：
```

2023-07-18 03:42 UTC, yanyongyu commented on website/docs/developer/adapter-writing.md
> +```
```suggestion
```python {20,25,34} title=bot.py
from typing import TYPE_CHECKING, Any, Union
from typing_extensions import override

from nonebot.message import handle_event
from nonebot.adapters import Bot as BaseBot

from .event import Event
from .message import Message, MessageSegment

if TYPE_CHECKING:
    from .adapter import Adapter


class Bot(BaseBot):
    """
    your_adapter_name 协议 Bot 适配。
    """

    @override
    def __init__(self, adapter: Adapter, self_id: str, **kwargs: Any):
        super().__init__(adapter, self_id)
        self.adapter: Adapter = adapter
        # 一些有关 Bot 的信息也可以在此定义和存储

    async def handle_event(self, event: Event):
        # 根据需要，对事件进行某些预处理，例如：
        # 检查事件是否和机器人有关操作，去除事件消息收尾的@bot
        # 检查事件是否有回复消息，调用平台API获取原始消息的消息内容
        ...
        # 调用 handle_event 让 NoneBot 对事件进行处理
        await handle_event(self, event)

    @override
    async def send(
        self,
        event: Event,
        message: Union[str, Message, MessageSegment],
        **kwargs: Any,
    ) -> Any:
        # 根据平台实现 Bot 回复事件的方法

        # 将消息处理为平台所需的格式后，调用发送消息接口进行发送，例如：
        data = message_to_platform_data(message)
        await self.send_message(
            data=data,
            ...
        )
```
```

2023-07-18 03:42 UTC, yanyongyu commented on website/docs/developer/adapter-writing.md
> +我们需要继承基类`Event`，实现一个适配器的基础`Event`，并实现相关方法：
```suggestion
Event 是 NoneBot 中的事件主体对象，所有平台消息在进入处理流程前需要转换为 NoneBot 事件。我们需要继承基类 `Event`，并实现相关方法：
```

2023-07-18 03:42 UTC, yanyongyu commented on website/docs/developer/adapter-writing.md
> +```
```suggestion
```python {6,9,14,19,24,29,34} title="event.py"
from typing_extensions import override

from nonebot.utils import escape_tag
from nonebot.adapters import Event as BaseEvent

class Event(BaseEvent):

    @override
    def get_event_name(self) -> str:
        # 返回事件的名称，用于日志打印
        return "event name"

    @override
    def get_event_description(self) -> str:
        # 返回事件的描述，用于日志打印，请注意转义 loguru tag
        return escape_tag(repr(self.dict()))

    @override
    def get_message(self):
        # 获取事件消息的方法，根据事件具体实现，如果事件非消息类型事件，则抛出异常
        raise ValueError("Event has no message!")

    @override
    def get_user_id(self) -> str:
        # 获取用户 ID 的方法，根据事件具体实现，如果事件没有用户 ID，则抛出异常
        raise ValueError("Event has no context!")

    @override
    def get_session_id(self) -> str:
        # 获取事件会话 ID 的方法，根据事件具体实现，如果事件没有相关 ID，则抛出异常
        raise ValueError("Event has no context!")

    @override
    def is_tome(self) -> bool:
        # 判断事件是否和机器人有关
        return False
```
```

2023-07-18 03:42 UTC, yanyongyu commented on website/docs/developer/adapter-writing.md
> +然后根据平台所给的事件，编写具体的`Event`，并且注意要实现`get_type`方法，返回事件对应的类型，具体请参考[事件类型](../advanced/adapter#事件类型)，消息类型事件还应重写`get_user_id`方法，例如：
```suggestion
然后根据平台消息的类型，编写各种不同的事件，并且注意要根据事件类型实现 `get_type` 方法，具体请参考[事件类型](../advanced/adapter#事件类型)，例如：
```

2023-07-18 03:42 UTC, yanyongyu commented on website/docs/developer/adapter-writing.md
> +我们需要继承`MessageSegment`和`Message`两个类，并实现相关方法：
```suggestion
Message 负责正确序列化消息，以便机器人插件处理。我们需要继承 `MessageSegment` 和 `Message` 两个类，并实现相关方法：
```

2023-07-18 03:42 UTC, yanyongyu commented on website/docs/developer/adapter-writing.md
> +```
```suggestion
```python {9,12,17,22,27,30,36} title="message.py"
from typing import Type, Iterable
from typing_extensions import override

from nonebot.utils import escape_tag

from nonebot.adapters import Message as BaseMessage
from nonebot.adapters import MessageSegment as BaseMessageSegment

class MessageSegment(BaseMessageSegment["Message"]):
    @classmethod
    @override
    def get_message_class(cls) -> Type["Message"]:
        # 返回适配器的Message类型本身
        return Message

    @override
    def __str__(self) -> str:
        # 返回该消息段的纯文本表现形式，通常在日志中展示
        return "text of MessageSegment"

    @override
    def is_text(self) -> bool:
        # 判断该消息段是否为纯文本
        return self.type == "text"


class Message(BaseMessage[MessageSegment]):
    @classmethod
    @override
    def get_segment_class(cls) -> Type[MessageSegment]:
        # 返回适配器的MessageSegment类型本身
        return MessageSegment

    @staticmethod
    @override
    def _construct(msg: str) -> Iterable[MessageSegment]:
        # 实现从字符串中构造消息数组，如无字符串嵌入格式可直接返回文本类型 MessageSegment
        ...
```
```

2023-07-18 03:42 UTC, yanyongyu commented on website/docs/developer/adapter-writing.md
> +在完成适配器代码的编写后，如果想要将适配器发布到 NoneBot 商店，我们需要将适配器发布到 PyPI中，前往[商店](https://nonebot.dev/store)页面，切换到适配器页签，点击 **发布适配器** 按钮，填写适配器相关信息并提交。
```suggestion
在完成适配器代码的编写后，如果想要将适配器发布到 NoneBot 商店，我们需要将适配器发布到 PyPI 中，然后前往[商店](/store)页面，切换到适配器页签，点击**发布适配器**按钮，填写适配器相关信息并提交。
```

2023-07-18 07:10 UTC, KomoriDev commented on website/docs/developer/adapter-writing.md
> +在完成适配器代码的编写后，如果想要将适配器发布到 NoneBot 商店，我们需要将适配器发布到 PyPI中，前往[商店](https://nonebot.dev/store)页面，切换到适配器页签，点击 **发布适配器** 按钮，填写适配器相关信息并提交。
~~我要有这语文素养，考试也不至于才80几~~

2023-07-31 12:21 UTC, MingxuanGame commented
可以提一下 nb-cli 创建适配器

`nb adapter create`

2023-08-10 06:45 UTC, yanyongyu requested changes

2023-08-10 06:45 UTC, yanyongyu commented on website/docs/developer/adapter-writing.md
> +```
```suggestion
```tree
📦 nonebot-adapter-{adapter-name}
├── 📂 nonebot
│   ├── 📂 adapters
│   │   ├── 📂 {adapter-name}
│   │   │   ├── 📜 __init__.py
│   │   │   ├── 📜 adapter.py
│   │   │   ├── 📜 bot.py
│   │   │   ├── 📜 config.py
│   │   │   ├── 📜 event.py
│   │   │   └── 📜 message.py
├── 📜 pyproject.toml
└── 📜 README.md
```
```

2023-08-10 06:45 UTC, yanyongyu commented on website/docs/developer/adapter-writing.md
> +    @override
override的import

2023-08-10 06:45 UTC, yanyongyu commented on website/docs/developer/adapter-writing.md
> +from nonebot.exception import WebSocketClosed
import格式化

2023-08-10 06:45 UTC, yanyongyu commented on website/docs/developer/adapter-writing.md
> +from .event import Event
import格式化

2023-08-10 06:45 UTC, yanyongyu commented on website/docs/developer/adapter-writing.md
> +    @overrides(BaseAdapter)
overrides换掉

2023-08-10 06:45 UTC, yanyongyu commented on website/docs/developer/adapter-writing.md
> +    @overrides(BaseEvent)
overrides替换

2023-08-10 06:45 UTC, yanyongyu commented on website/docs/developer/adapter-writing.md
> +    @overrides(BaseEvent)
overrides替换

2023-08-10 06:45 UTC, yanyongyu commented on website/docs/developer/adapter-writing.md
> +```
overrides替换

2023-08-13 03:17 UTC, yanyongyu approved these changes

2023-08-13 03:18 UTC, merged