Feature: 添加 `inherit_supported_adapters` 用于动态继承支持适配器数据
nonebot/nonebot2 pull request #2127
Opened 2023-06-25 14:37 UTC by NCBM

2023-06-26 02:33 UTC, yanyongyu requested changes

2023-06-26 02:33 UTC, yanyongyu commented on nonebot/plugin/load.py
> +def inherit_supported_adapters(*names: str) -> Optional[Set[str]]:
这个方法放到metadata的模块里

2023-06-26 02:33 UTC, yanyongyu commented on nonebot/plugin/load.py
> +            else adapter_name
这里不要缩写了全部展开

2023-06-26 02:36 UTC, yanyongyu commented
看着还是很诡异不适合放到这里面

2023-06-26 05:25 UTC, yanyongyu commented on nonebot/plugin/load.py
> +    )
？这个删了吧 💢

2023-06-26 05:26 UTC, NCBM commented on nonebot/plugin/load.py
> +    )
ok

2023-06-27 02:16 UTC, yanyongyu commented on nonebot/plugin/load.py
> +            adapter_name.replace("~", "nonebot.adapters.", 1)
不要用replace，用startswith判断

2023-06-27 02:16 UTC, yanyongyu commented on nonebot/plugin/load.py
> +        if final_supported is None
这里可以用and简写

2023-06-27 08:23 UTC, yanyongyu approved these changes

2023-06-27 08:25 UTC, merged