Feature: CommandGroup 支持命令别名添加前缀选项
nonebot/nonebot2 pull request #2134
Opened 2023-06-28 09:13 UTC by eya46

2023-06-28 09:18 UTC, yanyongyu commented
alias设计上就是不会添加前缀的

2023-06-28 13:44 UTC, eya46 commented
加个配置项怎么样

2023-06-28 15:39 UTC, yanyongyu commented
加到command group初始化的时候吧

2023-06-29 02:17 UTC, yanyongyu requested changes
还要添加测试用例和文档

2023-06-29 02:17 UTC, yanyongyu commented on nonebot/plugin/on.py
> +        affect_aliases: 是否影响命令别名，给命令别名加前缀
请按照参数顺序写docstring

2023-06-29 02:17 UTC, yanyongyu commented on nonebot/plugin/on.py
> +        self, cmd: Union[str, Tuple[str, ...]], affect_aliases: bool = False, **kwargs
参数名改一下
```suggestion
        self, cmd: Union[str, Tuple[str, ...]], prefix_aliases: bool = False, **kwargs
```

2023-06-29 02:17 UTC, yanyongyu commented on nonebot/plugin/on.py
> +        self.affect_aliases = affect_aliases
写在kwargs前面

2023-06-29 02:17 UTC, yanyongyu commented on nonebot/plugin/on.py
> +            kwargs["aliases"] = _aliases
```suggestion
            kwargs["aliases"] = {
                self.basecmd + ((alias,) if isinstance(alias, str) else alias)
                for alias in aliases
            }
```

2023-06-29 02:17 UTC, yanyongyu commented on nonebot/plugin/on.py
> +            kwargs["aliases"] = _aliases
这里和上面一样

2023-06-29 02:17 UTC, yanyongyu commented on nonebot/plugin/on.pyi
> +        affect_aliases: bool = ...,
参数应该在cmd后面*前面

2023-06-29 02:40 UTC, eya46 commented on nonebot/plugin/on.pyi
> +        affect_aliases: bool = ...,
```python
class CommandGroup(_Group):
    """命令组，用于声明一组有相同名称前缀的命令。

    参数:
        cmd: 指定命令内容
        prefix_aliases: 是否影响命令别名，给命令别名加前缀
        rule: 事件响应规则
        permission: 事件响应权限
        handlers: 事件处理函数列表
        temp: 是否为临时事件响应器（仅执行一次）
        expire_time: 事件响应器最终有效时间点，过时即被删除
        priority: 事件响应器优先级
        block: 是否阻止事件向更低优先级传递
        state: 默认 state
    """

    def __init__(
        self, cmd: Union[str, Tuple[str, ...]], prefix_aliases: bool = False, **kwargs
    ):
```
```python
class CommandGroup:
    def __init__(
        self,
        cmd: str | tuple[str, ...],
        prefix_aliases: bool = ...,
        *,
        rule: Rule | T_RuleChecker | None = ...,
        permission: Permission | T_PermissionChecker | None = ...,
        handlers: list[T_Handler | Dependent] | None = ...,
        temp: bool = ...,
        expire_time: datetime | timedelta | None = ...,
        priority: int = ...,
        block: bool = ...,
        state: T_State | None = ...,
    ): ...
```
这样改吗

2023-06-30 02:24 UTC, yanyongyu requested changes

2023-06-30 02:24 UTC, yanyongyu commented on website/docs/advanced/matcher.md
> +如果需要为aliases设置前缀，可以添加 `prefix_aliases=True` 参数:
```suggestion
命令别名 aliases 默认不会添加 `CommandGroup` 设定的前缀，如果需要为 aliases 添加前缀，可以添加 `prefix_aliases=True` 参数:
```

2023-06-30 02:24 UTC, yanyongyu commented on website/docs/advanced/matcher.md
> +sub_cmd = group.command("sub", aliases={"subs"})
```suggestion
```

2023-06-30 02:24 UTC, yanyongyu commented on website/docs/advanced/matcher.md
> +如果未设置，将默认匹配 `/cmd`、`/cmd.sub`、`/subs`、`/cmd.help`、`/帮助` 五个命令。
```suggestion
这样就能成功匹配 `/cmd`、`/cmd.help`、`/cmd.帮助` 命令。如果未设置，将默认匹配 `/cmd`、`/cmd.help`、`/帮助` 命令。
```

2023-06-30 02:25 UTC, yanyongyu commented
还有测试没添加

2023-07-01 05:51 UTC, yanyongyu commented on website/docs/advanced/matcher.md
> +sub_cmd = group.command("sub", aliases={"subs"})
这个没删掉啊

2023-07-01 07:39 UTC, yanyongyu approved these changes

2023-07-01 07:40 UTC, merged