设置默认filename为name，补对应的测试
nonebot/nonebot2 pull request #2284
Opened 2023-08-18 03:50 UTC by eya46

~`{name:FileContent} -> (name, (None, FileContent, None))`~
`{name:FileContent} -> (name, (name, FileContent, None))`

httpx驱动器上传失败 #1647 

nb model.py内会把`files={"test":b"test"}`处理成，`("test", (None, b"test", None))`

> httpx

当FileTypes为`bytes`，不是`Tuple[Optional[str], FileContent, Optional[str]]`时，httpx会默认`file_name="upload"`
但传的是 `Tuple[None, FileContent, Optional[str]]` ，httpx会处理成FileField -> `(None, b'test')`
( 这会导致server端收不到文件?
```python
# httpx/_multipart.py
if isinstance(value, tuple):
    if len(value) == 2:
        # neither the 3rd parameter (content_type) nor the 4th (headers) was included
        filename, fileobj = value  # type: ignore
    elif len(value) == 3:
        filename, fileobj, content_type = value  # type: ignore
    else:
        # all 4 parameters included
        filename, fileobj, content_type, headers = value  # type: ignore
else:
    filename = Path(str(getattr(value, "name", "upload"))).name
```

> aiohttp

没看(

test_file
```python
files=[
    ("test1", b"test"),
    ("test2", ("test.txt", b"test")),
    ("test3", ("test.txt", b"test", "text/plain")),
]

response = await driver.request(request)
data = json.loads(response.content)

// httpx {"test2": "test", "test3": "test"}, "报错""file parsing error"
assert data["files"] == {
    "test1": "test",
    "test2": "test",
    "test3": "test",
}, "file parsing error"

// aiohttp ok
```

2023-08-21 02:55 UTC, yanyongyu reviewed
请处理pyright linter check错误部分

2023-08-21 11:26 UTC, eya46 commented
改了下

2023-08-22 02:29 UTC, yanyongyu requested changes

2023-08-22 02:29 UTC, yanyongyu commented on tests/test_driver.py
> +
请把这一块合并到上方的files测试中

2023-08-22 11:47 UTC, eya46 commented on tests/test_driver.py
> +
🌟⭐🌟

2023-08-23 03:05 UTC, yanyongyu requested changes

2023-08-23 03:05 UTC, yanyongyu commented on tests/test_driver.py
> +
不是我是说这块为啥不和上面post with files and form data合并

2023-08-23 06:09 UTC, yanyongyu approved these changes

2023-08-23 06:14 UTC, merged