Docs: 更新 Pydantic 相关使用文档
nonebot/nonebot2 pull request #2563
Opened 2024-02-04 09:08 UTC by yanyongyu

2024-02-04 12:01 UTC, MingxuanGame requested changes
在 配置 一节的开头加一下：文档中使用的是 pydantic v2

2024-02-05 05:23 UTC, he0119 approved these changes

2024-02-05 05:23 UTC, he0119 commented on nonebot/plugin/__init__.py
> +def get_plugin_config(config: Type[C]) -> C:
都加新功能是不是不该叫 Docs 了（

2024-02-05 05:47 UTC, MingxuanGame commented on website/docs/appendices/config.mdx
> +from nonebot import get_driver, get_plugin_config
`get_driver` 未使用

2024-02-05 05:47 UTC, MingxuanGame commented on website/docs/appendices/config.mdx
> +from nonebot import get_driver, get_plugin_config
`get_driver` 未使用

2024-02-05 05:51 UTC, MingxuanGame approved these changes

2024-02-05 06:00 UTC, merged