Fix: `fastapi` 中轮询启用 `HTTP2` 的逻辑
nonebot/nonebot2 pull request #614
Opened 2021-12-02 07:42 UTC by NekoAria

resolved nonebot/adapter-telegram#3

2021-12-02 08:10 UTC, yanyongyu commented
setup可能是callable所以不能这么写

2021-12-02 08:12 UTC, NekoAria commented
> setup可能是callable所以不能这么写

那么麻烦你改一下吧（

2021-12-02 08:12 UTC, yanyongyu requested changes
需要重写client建立逻辑

2021-12-02 12:55 UTC, yanyongyu commented
因为 dev 分支改动较大，现有master合并冲突，新开了个分支修复 #615

2021-12-04 15:09 UTC, yanyongyu commented
fixed in #615 Thanks for pr!

2021-12-04 15:09 UTC, closed without merging