:memo: Add CONTRIBUTING
nonebot/nonebot2 pull request #745
Opened 2022-01-26 12:41 UTC by j1g5awi

2022-01-26 13:16 UTC, mnixry reviewed
随便改了几行, 没按照中文排版规范来, 你再改改)

2022-01-26 13:16 UTC, mnixry commented on CONTRIBUTING.md
> +### 报告漏洞
```suggestion
### 报告问题/故障/Bug
```

2022-01-26 13:16 UTC, mnixry commented on CONTRIBUTING.md
> +NoneBot2 还未进入正式版，欢迎建议我们要加入哪些新功能。不过由于 NoneBot 已经进入 beta 开发阶段，请尽量让新的功能不破坏对旧版本的兼容性。
```suggestion
NoneBot2 还未进入正式版，欢迎在Issue中提议要加入哪些新功能

为了让其他开发者们更好地理解你的意图, 请认真填写预期行为等内容, 如果可能, 可以提出可行的解决方案猜想
```

2022-01-26 13:16 UTC, mnixry commented on CONTRIBUTING.md
> +
```suggestion

### Commit提交规范

```

2022-01-26 13:16 UTC, mnixry commented on CONTRIBUTING.md
> +如果你已经是 NoneBot 团队的成员，请注意千万不要直接 commit 到 `dev` 分支。你必须创建新的分支以提出 Pull Request，并邀请其他团队成员审计代码，以防止开发分支出错。
```suggestion
```

这句话直接删了吧 大家都知道, 放在这感觉有点凡尔赛)

2022-01-26 13:16 UTC, mnixry commented on CONTRIBUTING.md
> +
```suggestion

请确保你的每一条commit都有清晰的描述它做了什么, 一个commit尽量只做一件事情

```

2022-01-26 14:47 UTC, StarHeartHunt commented on CONTRIBUTING.md
> +如果你不是 NoneBot 团队的成员，自行 fork 后即可提出 Pull Request，请尤其注意在前面提到的 commit message 规范，
```suggestion
如果你不是 NoneBot 团队的成员，可在 fork 本仓库后，向本仓库的 `dev` 分支发起 Pull Request 提交贡献，注意遵循先前提到的 commit message 规范创建 commit，
```

2022-01-26 14:47 UTC, StarHeartHunt commented on CONTRIBUTING.md
> +NoneBot2 还未进入正式版，欢迎建议我们要加入哪些新功能。不过由于 NoneBot 已经进入 beta 开发阶段，请尽量让新的功能不破坏对旧版本的兼容性。
注意 Issue 左右空格和末尾句号（。）

2022-01-26 14:47 UTC, StarHeartHunt commented on CONTRIBUTING.md
> +NoneBot 的 commit message 遵循 [gitmoji](https://gitmoji.dev/) 规范，在 commit 时请牢记这一点。
```suggestion
NoneBot 的 commit message 格式遵循 [gitmoji](https://gitmoji.dev/) 规范，在创建 commit 时请牢记这一点。
```

2022-01-26 14:47 UTC, StarHeartHunt commented on CONTRIBUTING.md
> +
commit 左右空格和末尾句号（。）

2022-01-26 14:47 UTC, StarHeartHunt commented on CONTRIBUTING.md
> +如果你想要上架的插件是其他插件的 fork，请遵守开源协议，以及补充自己相较于原版的区别。
```suggestion
同时，如果你参考或基于他人发行的代码进行开发，请注意遵守各代码所使用的的开源许可协议。
```

2022-01-26 14:47 UTC, StarHeartHunt commented on CONTRIBUTING.md
> +我们仅对插件的兼容性进行简单测试，并在下一个版本发布前处理不兼容的插件。
```suggestion
我们仅对插件的兼容性进行简单测试，并会在下一个版本发布前对与该版本不兼容的插件作出处理。
```

2022-01-26 14:47 UTC, StarHeartHunt commented on CONTRIBUTING.md
> +虽然对插件的内容没有严格限制，但我们还是建议在上架插件之前先查看商店有无功能一致的插件。
```suggestion
虽然对插件的内容没有严格限制，但我们还是建议在上架插件之前先查看商店有无功能一致的插件。如果你想要上架商店的插件的功能与现有插件的功能不完全重合，请在插件说明中补充与现有插件存在的区别。
```

2022-01-26 14:49 UTC, StarHeartHunt commented on CONTRIBUTING.md
> +本指南旨在引导你更加恰当地为 NoneBot2 做贡献，请务必认真阅读。
本指南旨在引导你更规范地向 NoneBot2 提交贡献，请务必认真阅读。

2022-01-26 14:56 UTC, StarHeartHunt commented on CONTRIBUTING.md
> +
Commit 左右空格

2022-01-27 13:31 UTC, yanyongyu requested changes

2022-01-27 13:31 UTC, yanyongyu commented on CONTRIBUTING.md
> +precommit install
```suggestion
pre-commit install
```

2022-01-27 15:45 UTC, yanyongyu requested changes

2022-01-27 15:45 UTC, yanyongyu commented on CONTRIBUTING.md
> +你可以在 NoneBot 商店上架自己的适配器、插件、机器人，具体步骤可参考 [发布插件](https://v2.nonebot.dev/docs/next/advanced/publish-plugin) 一节。
```suggestion
你可以在 NoneBot 商店上架自己的适配器、插件、机器人，具体步骤可参考 [发布插件](https://v2.nonebot.dev/docs/advanced/publish-plugin) 一节。
```

2022-01-27 15:45 UTC, yanyongyu commented on CONTRIBUTING.md
> +如果你需要在本地预览修改后的文档，可以使用 yarn 或 npm 等 Nodejs 的依赖管理工具安装文档依赖后自行部署。
```suggestion
NoneBot2 的文档使用 [docusaurus](https://docusaurus.io/)，它有一些 [Markdown 特性](https://docusaurus.io/zh-CN/docs/markdown-features) 可能会帮助到你。

NoneBot2 文档并没有具体的行文风格规范，但我们建议你尽量写得简单易懂。

如果你需要在本地预览修改后的文档，可以使用 yarn 安装文档依赖后启动 dev server。
```

2022-01-27 15:45 UTC, yanyongyu commented on CONTRIBUTING.md
> +如果你需要在本地预览修改后的文档，可以使用 yarn 或 npm 等 Nodejs 的依赖管理工具安装文档依赖后自行部署。
这边只能用yarn

再加个

```bash
yarn install
yarn start
```

2022-01-28 05:58 UTC, yanyongyu approved these changes

2022-01-28 06:05 UTC, merged