添加 `fastapi_reload` 在 win 的额外影响
nonebot/nonebot2 pull request #830
Opened 2022-02-20 14:51 UTC by CherryGS

在 python 3.8 之后 , win平台默认使用 `ProactorEventLoop` , 而 uvicorn 在启动 `reload` 后会强制绑定默认事件循环为 `SelectorEventLoop` , 后者在 win 平台的可使用性不如前者 , 也会导致一些使用 asyncio 的包出错(如 playwright) 
(见[uvicorn#529](https://github.com/encode/uvicorn/issues/529)

2022-02-20 15:36 UTC, mnixry commented
根据 @SK-415 反馈, 似乎beta2锁定的uvicorn版本`^0.17.0` 又强制换回了SelectorEventLoop, 然后彻底禁用了Windows平台的重载, 你可以检查一下是不是这样

2022-02-20 15:50 UTC, CherryGS commented
环境
![捕获](https://user-images.githubusercontent.com/61844819/154851046-7a752074-c0ee-4044-a80e-99344b480dfe.PNG)
![0](https://user-images.githubusercontent.com/61844819/154851048-0e65a9ba-282b-4cef-93d9-4f767d42b5b5.PNG)

代码
![2](https://user-images.githubusercontent.com/61844819/154851083-07d3d16d-0e62-4831-927d-ceea1fc1e946.PNG)
![1](https://user-images.githubusercontent.com/61844819/154851094-03301cc0-9eda-40ff-8e79-f58e8d8f8db1.PNG)

不开启 `reload`
![3](https://user-images.githubusercontent.com/61844819/154851133-1d7704da-949a-48c9-8844-735a5b4329b7.PNG)

开启 `reload`
![4](https://user-images.githubusercontent.com/61844819/154851180-06768d5a-a008-41de-b8a9-f85296db2721.PNG)

开启 `reload` 后启动会有 warning
![5](https://user-images.githubusercontent.com/61844819/154851251-79f322ad-6e90-491c-8feb-39ec9f2c114a.PNG)

2022-02-20 18:09 UTC, SK-415 commented
你说的情况在低版本 `uvicorn<=1.14.0` 中确实存在，Windows 系统下默认的 `ProactorEventLoop` 会被替换为 `SelectorEventLoop`，进而导致需要调用 `asyncio.subprocess.create_subprocess_*` 的库，如 Playwright 无法正常工作，我也曾贴出过一个 [补丁](https://github.com/nonebot/nonebot2/issues/376#issuecomment-846523618) 解决这个问题。

但是在 https://github.com/encode/uvicorn/pull/1070 中，Windows 下的默认事件循环被替换为了 `WindowsSelectorEventLoopPolicy` 而非 `SelectorEventLoop`。经过测试，Playwright 可以在这个事件循环下正常工作，无需做任何修改。

然后在 https://github.com/encode/uvicorn/pull/1257 中，Windows 系统即使带了 `--reload` 参数也会被 Uvicorn 忽视不会生效。

上述改动在 `uvicorn>=1.16.0` 之后均有效，因此只要保证 Uvicorn 为较新版本就不存在 https://github.com/encode/uvicorn/issues/529 的问题。

2022-02-20 18:27 UTC, CherryGS commented
又去试了一下
如果在 `nonebot.run()` 里传参  `reload=True` , reload 会被禁用
如果在 env 里定义 `fastapi_reload=true` , reload 会被启用 , 有一条 `warning`
cli 启动不会用 , 这个就不太清楚了

而某个版本以上 , `WindowsSelectorEventLoopPolicy ` 的默认行为是 `ProactorEventLoop`
![](https://user-images.githubusercontent.com/61844819/154857894-4c91cfc1-0e69-4e4f-8dc1-85c4598e541d.PNG)
(python3.10.2)

但是在 reload 行为中 , 默认的事件循环被 uvicorn 替换成了 `SelectorEventLoop`

2022-02-20 18:36 UTC, CherryGS commented
![0](https://user-images.githubusercontent.com/61844819/154858253-0c334899-f4e3-4f4f-8667-a0220933790c.PNG)
在这个版本下 , 添加 reload 行为启动后 playwright 仍然会报错 , 这也是 pypi 能获取到的最高版本了

2022-02-20 18:57 UTC, SK-415 commented
确认，问题确实依然存在，感谢指正。

我没有注意到 Nonebot2 增加了 `fastapi_reload` 配置且默认为 False，导致我误以为启动了 reload 模式，实则根据 https://github.com/encode/uvicorn/pull/1257 使用的依然是默认事件循环。

改正后重新测试，确认使用的是 `SelectorEventLoop`，Playwright 等库依然无法使用。

2022-02-20 19:17 UTC, SK-415 commented
但是我觉得这条提示的信息量有点少，对于没有经验的开发者很难意识到 “事件循环强制绑定到 `SelectorEventLoop`” 会有什么影响。

我的建议是找个地方（比如就这里）总结一下可能产生的问题，并在提示最后加一句类似于：“可能导致部分库无法正常运行（详见……）” 并附上总结的链接。

2022-02-21 04:19 UTC, yanyongyu requested changes

2022-02-21 04:19 UTC, yanyongyu commented on website/versioned_docs/version-2.0.0-beta.2/tutorial/choose-driver.md
> +说明：是否开启 `uvicorn` 的 `reload` 功能，需要提供 asgi 应用路径 (在 win 平台开启后会使事件循环强制绑定到`selectoreventloop`上)。
不如在下方用admonitionsi详细说明

```
:::warning 警告
blabla
:::
```

2022-02-21 11:10 UTC, CherryGS commented on website/versioned_docs/version-2.0.0-beta.2/tutorial/choose-driver.md
> +说明：是否开启 `uvicorn` 的 `reload` 功能，需要提供 asgi 应用路径 (在 win 平台开启后会使事件循环强制绑定到`selectoreventloop`上)。
好, 我去完善一下

2022-02-21 14:39 UTC, mnixry approved these changes
感谢PR, 可以稍微改一下上述这些地方的表述

另外请将修改后的文档同步到[`website/docs/tutorial`](https://github.com/nonebot/nonebot2/tree/master/website/docs/tutorial), 以便使未来版本的文档也包含该更改

2022-02-21 14:39 UTC, mnixry commented on website/versioned_docs/version-2.0.0-beta.2/tutorial/choose-driver.md
> +在 python 版本大于等于 3.8 下 , 开启该功能后 , 在 uvicorn 运行时 (fastapi 底层 , reload 功能的实际来源) , asyncio 使用的事件循环会被 uvicorn 从默认的 `ProactorEventLoop` 强制切换到 `SelectorEventLoop`
```suggestion
在 `Python>=3.8` 环境下开启该功能后 , 在 uvicorn 运行时 (FastAPI提供的ASGI底层 , 即reload 功能的实际来源) , asyncio 使用的事件循环会被 uvicorn 从默认的 `ProactorEventLoop` 强制切换到 `SelectorEventLoop`
```

2022-02-21 14:39 UTC, mnixry commented on website/versioned_docs/version-2.0.0-beta.2/tutorial/choose-driver.md
> +在 windows 平台上开启该功能会可能会有额外的影响
```suggestion
在 Windows 平台上开启该功能会可能会有额外的影响
```

2022-02-21 14:39 UTC, mnixry commented on website/versioned_docs/version-2.0.0-beta.2/tutorial/choose-driver.md
> +后者在 windows 平台的可使用性不如前者 , 包括但不限于
```suggestion
后者(`ProactorEventLoop`)在 windows 平台的可使用性不如前者(`SelectorEventLoop`) , 包括但不限于
```

2022-02-21 14:39 UTC, mnixry commented on website/versioned_docs/version-2.0.0-beta.2/tutorial/choose-driver.md
> +具体信息见 [python doc](https://docs.python.org/zh-cn/3.10/library/asyncio-platforms.html#windows)
```suggestion
具体信息见 [Python 文档](https://docs.python.org/zh-cn/3/library/asyncio-platforms.html#windows)
```

2022-02-21 14:39 UTC, mnixry commented on website/versioned_docs/version-2.0.0-beta.2/tutorial/choose-driver.md
> +> 具体信息见 [python doc](https://docs.python.org/zh-cn/3.10/library/asyncio-platforms.html#windows)
```suggestion
> 具体信息见 [Python 文档](https://docs.python.org/zh-cn/3.10/library/asyncio-platforms.html#windows)
```

2022-02-21 14:39 UTC, mnixry commented on website/versioned_docs/version-2.0.0-beta.2/tutorial/choose-driver.md
> +在 windows 平台上开启该功能会有额外的影响
```suggestion
在 Windows 平台上开启该功能有可能会造成预料之外的影响!
```

2022-02-21 14:39 UTC, mnixry commented on website/versioned_docs/version-2.0.0-beta.2/tutorial/choose-driver.md
> +windows 平台上 , 在 python 版本大于等于 3.8 下 , 开启该功能后 , 在 uvicorn 运行时 (fastapi 底层 , reload 功能的实际来源) , asyncio 使用的事件循环会被 uvicorn 从默认的 `ProactorEventLoop` 强制切换到 `SelectorEventLoop`
```suggestion
在 Windows 平台上 , `Python>=3.8` 的情况下 , 在开启该功能后 , 在 uvicorn 运行时 (FastAPI 等基于 ASGI 的服务底层 , reload 能力的实际提供者) , asyncio 使用的事件循环会被 uvicorn 从默认的 `ProactorEventLoop` 强制切换到 `SelectorEventLoop`
```

2022-02-21 14:39 UTC, mnixry commented on website/versioned_docs/version-2.0.0-beta.2/tutorial/choose-driver.md
> +> windows 平台上 , 在 python 版本小于 3.8 时 , 默认的事件循环是 `SelectorEventLoop`
```suggestion
```

要不直接删了这句吧

2022-02-21 14:42 UTC, CherryGS commented on website/versioned_docs/version-2.0.0-beta.2/tutorial/choose-driver.md
> +> windows 平台上 , 在 python 版本小于 3.8 时 , 默认的事件循环是 `SelectorEventLoop`
也是，应该没有多少人用3.8以下了(

2022-02-22 14:42 UTC, mnixry approved these changes
感谢PR，将会在稍后合并。

2022-02-22 15:10 UTC, merged