Update deployment.md
nonebot/nonebot2 pull request #847
Opened 2022-03-02 14:09 UTC by evlic

添加 pm2 部署的相关示例

2022-03-02 14:21 UTC, mnixry requested changes
nonebot2推荐使用nb-cli运行机器人
常见指令是`nb run`（或者等价指令`python -m nb_cli run`）
需要修改一下

2022-03-02 14:21 UTC, mnixry commented on website/versioned_docs/version-2.0.0-beta.2/tutorial/deployment.md
> +- Minot 监控
```suggestion
- Monit 监控
```

2022-03-02 16:12 UTC, mnixry requested changes
麻烦再改一下)

2022-03-02 16:12 UTC, mnixry commented on website/versioned_docs/version-2.0.0-beta.2/tutorial/deployment.md
> +pm2 start -n '{bot_name}' -x 'cd {bot_dir} && nb run {bot_run.py}'
```suggestion
cd {bot_dir}
pm2 start -n '{bot_name}' -x 'python -m nb_cli run'
```
这样稳一点

2022-03-02 17:20 UTC, evlic commented on website/versioned_docs/version-2.0.0-beta.2/tutorial/deployment.md
> +> 由于虚拟环境中，大概率不会自带 nb-cli，且为了避免未知 Bug，建议使用对应的原始启动方式。
我这边用下来是可以接受环境变量的，执行 poetry shell 也会直接 source 对应的环境变量。

这是我当前用 pm2 部署用的 shell 指令
```shell
SUDO_COMMAND: /usr/bin/pm2 start -n zxbot -x su - ubuntu -c " cd {} && source /home/ubuntu/.cache/pypoetry/virtualenvs/{}/bin/activate && python3 bot.py" ```

2022-03-03 07:09 UTC, evlic commented
> 麻烦再改一下)

已完成修改，可以合并。

2022-03-04 08:00 UTC, closed without merging