:memo: Add unittest docs
nonebot/nonebot2 pull request #929
Opened 2022-04-17 18:26 UTC by MingxuanGame

简单写了写 NoneBug 单元测试的文档
包含了概览，测试事件响应操作，规则和权限操作，测试依赖注入和测试适配器
其他的因为社区开发大概率用不上所以没写 ~~写了估计也用不上，有需求我再写~~
可能语法有疏漏的地方，也请多多指正修改

2022-04-18 15:23 UTC, yanyongyu commented
md里头部的frontmatter只要一个主入口指定menu option就够了，另外是有缩进的

```
options:
  menu:
    weight:
    category:
```

2022-04-24 10:11 UTC, yanyongyu requested changes
`unittest/unittest.mdx` 能否改个名字 `unittest/README.mdx` 然后在 frontmatter 里添加一下
`slug: /advanced/unittest/`

2022-04-24 12:35 UTC, yanyongyu requested changes

2022-04-24 12:35 UTC, yanyongyu commented on website/docs/advanced/unittest/README.mdx
> +import WeatherTest from "!!raw-loader!@site/../tests/test_examples/test_weather.py";
前面多空了一行，标题解析错误

2022-04-24 12:35 UTC, yanyongyu commented on website/docs/advanced/unittest/README.mdx
> +安装 NoneBug 时，Pytest 及其异步插件 `pytest-asyncio` 会作为依赖被一起安装。
nonebug并没有依赖`pytest-asyncio`，安装时用户需要自行选择安装`pytest-asyncio`或者`anyio`

2022-04-24 12:35 UTC, yanyongyu commented on website/docs/advanced/unittest/README.mdx
> +    return nonebot.load_plugins(str(Path(__file__).parent / "examples"))
这里的路径应该根据项目目录修改

2022-04-24 12:40 UTC, MingxuanGame commented on website/docs/advanced/unittest/README.mdx
> +安装 NoneBug 时，Pytest 及其异步插件 `pytest-asyncio` 会作为依赖被一起安装。
> nonebug并没有依赖`pytest-asyncio`，安装时用户需要自行选择安装`pytest-asyncio`或者`anyio`

在nonebug的pyproject.toml中`dev-dependencies`存在依赖`pytest-asyncio`

https://github.com/nonebot/nonebug/blob/master/pyproject.toml#L27

或许需要提醒用户

2022-04-24 12:54 UTC, yanyongyu commented on website/docs/advanced/unittest/README.mdx
> +安装 NoneBug 时，Pytest 及其异步插件 `pytest-asyncio` 会作为依赖被一起安装。
dev依赖不会在用户安装时被安装，文档应该说明二选一自行安装

2022-04-24 14:50 UTC, yanyongyu commented on website/docs/advanced/unittest/README.mdx
>  # --dev 参数是可选的，表示为开发依赖项
```suggestion
```

2022-04-24 14:52 UTC, yanyongyu commented
标题还是有解析错误啊 怪

![image](https://user-images.githubusercontent.com/42488585/164982346-6912fe7c-92b3-49a2-b17f-824ee4d4d43c.png)

2022-04-24 14:54 UTC, yanyongyu commented on website/docs/advanced/unittest/README.mdx
> +category: advanced
这里的缩进没了

2022-04-25 02:31 UTC, StarHeartHunt commented
> 标题还是有解析错误啊 怪
> 
> ![image](https://user-images.githubusercontent.com/42488585/164982346-6912fe7c-92b3-49a2-b17f-824ee4d4d43c.png)

好像 mdx 在文件开头 import 的话自动解析 h1 会失效，看 [docusaurus 的 mdx](https://github.com/facebook/docusaurus/blob/main/website/docs/guides/markdown-features/markdown-features-headings.mdx) 都是用 title 单独指定。

2022-04-25 04:05 UTC, yanyongyu commented
> 好像 mdx 在文件开头 import 的话自动解析 h1 会失效，看 [docusaurus 的 mdx](https://github.com/facebook/docusaurus/blob/main/website/docs/guides/markdown-features/markdown-features-headings.mdx?rgh-link-date=2022-04-25T02%3A31%3A19Z) 都是用 title 单独指定。

import 多了好像会失效，但是一行就没问题，很怪

2022-04-25 06:24 UTC, MingxuanGame commented on website/docs/advanced/unittest/README.mdx
> +Fixture 名称 `load_plugins` 可以修改为其他名称，文档以 `load_plugins` 为例。需要加载插件时，在测试函数添加形参 `load_plugins` 即可。加载完成后即可使用 `import` 导入事件响应器。
这里的名称为`load_plugins`，但是下面的例子（即`test_weather.py`）中使用的是`load_example`，应在提示中予以说明

2022-04-30 08:02 UTC, yanyongyu approved these changes

2022-04-30 08:04 UTC, merged